### ISSUE TITLE
New 0.2.7 version gives me serialization error. Downgrade to 0.2.6 is OK

### ISSUE THREAD

**Issue by thondeboer** [streamsync-cloud/streamsync#118]
I updated the 0.2.7 but got a massive amount of serialization errors on my app, that works fine on 0.2.6.

```
6Sep2023 00:32:57-ERROR   -|core              | From app log: 
Serialisation Error
An exception was raised during serialisation.
Traceback (most recent call last):
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 248, in get_mutations_as_dict
    serialised_value = state_serialiser.serialise(value)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 122, in serialise
    return self._serialise_matplotlib_fig(v)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 155, in _serialise_matplotlib_fig
    fig.savefig(iobytes, format="png")
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2336, in print_figure
    renderer = _get_renderer(
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1598, in _get_renderer
    print_method(io.BytesIO())
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 457, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1588, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7f7962aab4f0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/app_runner.py", line 191, in _handle_state_enquiry
    mutations = session.session_state.user_state.get_mutations_as_dict()
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 239, in get_mutations_as_dict
    child_mutations = value.get_mutations_as_dict()
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 239, in get_mutations_as_dict
    child_mutations = value.get_mutations_as_dict()
  File "/home/tdeboer/.cache/pypoetry/virtualenvs/rnayx-eqgCBscA-py3.10/lib/python3.10/site-packages/streamsync/core.py", line 250, in get_mutations_as_dict
    raise ValueError(
ValueError: Couldn't serialise value of type "<class 'matplotlib.figure.Figure'>" for key "heatmap".
```

I have a handler that does not even update the plotly plot I intercept the click even from, but it seems related to the Figures I have in matplotlib

**Comment by thondeboer** [comment]
Great to have the logs in the console though, since UI is too slow for my complex app.

**Comment by thondeboer** [comment]
I think I have narrowed it down to a problem with a module I am using...PyComplexHeatmap.
When I just import one of the modules I need, i messes up matplotlib somehow...I will continue to investigate, but unlikley issue with streamsync, so will reopen when I feel it still is issue with SS, but I see something similar in DASH, so unlikely
