### ISSUE TITLE
Latest master doesn't build

### ISSUE THREAD

**Issue by aleloi** [streamsync-cloud/streamsync#210]
To reproduce try building according to this Dockerfile:

```Dockerfile
FROM node:slim AS components-image
RUN apt-get update && \
    apt-get install -y git
WORKDIR /app
RUN git clone https://github.com/streamsync-cloud/streamsync.git streamsync_master
WORKDIR /app/streamsync_master/ui
RUN git checkout v0.3.0
RUN npm install
# RUN npm install ag-grid-community
# COPY project/custom_components/ /app/streamsync_master/ui/src/custom_components
# RUN npm run custom.build
# RUN mkdir /custom_components
# RUN mv custom_components_dist/ /custom_components
RUN npm run build  # This doesn't work, bug somewhere
```

It can't find BuilderFieldsWidth.vue in the repo:

```
> [components-image 13/13] RUN npm run build:
0.532 
0.532 > streamsync-ui@0.0.0 build
0.532 > vite build
0.532 
0.732 vite v4.4.9 building for production...
0.958 transforming...
6.459 ✓ 306 modules transformed.
6.459 ✓ built in 5.73s
6.460 Could not resolve "./BuilderFieldsWidth.vue" from "src/builder/BuilderSettingsProperties.vue?vue&type=script&setup=true&lang.ts"
6.460 file: /app/streamsync_master/ui/src/builder/BuilderSettingsProperties.vue?vue&type=script&setup=true&lang.ts
6.462 error during build:
6.462 RollupError: Could not resolve "./BuilderFieldsWidth.vue" from "src/builder/BuilderSettingsProperties.vue?vue&type=script&setup=true&lang.ts"
6.462     at error (file:///app/streamsync_master/ui/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
6.462     at ModuleLoader.handleInvalidResolvedId (file:///app/streamsync_master/ui/node_modules/rollup/dist/es/shared/node-entry.js:24736:24)
6.462     at file:///app/streamsync_master/ui/node_modules/rollup/dist/es/shared/node-entry.js:24698:26
```

**Comment by ramedina86** [comment]
I believe I managed to fix it, I also moved the v0.3.0 tag so that it points to the latest commit. Build from `master` worked for me now, but if you can confirm too I'd appreciate it.

Thanks for reporting this and apologies for the trouble.

**Comment by FabienArcellier** [comment]
The build using the Dockerfile from @aleloi is working for me using `master`. I am able to run the full build through `build.sh`.

**Comment by ramedina86** [comment]
Perfect, thanks @FabienArcellier
